### ISSUE TITLE
AutoCraft TODO list

### ISSUE THREAD

**Issue by ReinforceZwei** [ReinforceZwei/Minecraft-Console-Client#1]
Core functions
- [x] Item stacking mechanism, item stack limit, stackable/non-stackable item
- [x] Shift click handling
- [x] Auto dropping items
- [x] Search and open crafting table
- [x] Auto crafting

Improvement list
- [ ] Able to handle item left in the crafting area
- [ ] Try to empty some space if inventory is full while crafting
- [ ] Able to choose between drop crafted item or keep it 
- [ ] Able to decide the quantity of crafted item
- [ ] Split item stack if possible (stack of x64 diamond split to 9 stacks for crafting diamond block)

Related improvement:
- [x] Write item moving methods in Container class
